// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataLocalityAdvisor.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAnalyzeCodePackageString = "6ddeaeb1-dec4-4ffa-8341-eb7102968291";
        public const string guidAnalyzeCodePackageCmdSetString = "91d753df-93d6-4d91-ab75-535cc3169dad";
        public const string guidImagesString = "1be07da1-faa6-4fcf-9a64-d2abd3647ef7";
        public static Guid guidAnalyzeCodePackage = new Guid(guidAnalyzeCodePackageString);
        public static Guid guidAnalyzeCodePackageCmdSet = new Guid(guidAnalyzeCodePackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TopLevelMenu = 0x1021;
        public const int btAnalyze = 0x0100;
        public const int btOptimizeRuntime = 0x0200;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
